_commit: v0.4.6
_src_path: https://github.com/will-rice/papers-template.git
project_name: Speech Enhancement Papers
project_slug: speech-enhancement-papers
template_version: 0.1.0
topic_description: Research papers on speech enhancement, denoising, dereverberation,
    and restoration
